include:
   - infra.yaml
services:
  web:
    build: .
    ports:
      - "8000:5000"
    develop:
      watch:
        - action: sync
          path: /home/user/Modul-109/composetest/infra.yaml
          target: /code
